package com.dipien.byebyedeadcode.code.filter

import com.dipien.byebyedeadcode.code.DeadCode

/**
 * Filters out the code that cannot be removed from the source code. For
 * example, a class generated by kapt or code generated by the
 * Kotlin compiler.
 */
interface DeadCodeFilter {

    fun filter(deadCode: DeadCode): DeadCode?
}
