package com.dipien.byebyedeadcode.code.filter

import com.dipien.byebyedeadcode.code.DeadCode
import com.dipien.byebyedeadcode.commons.LoggerHelper

/**
 * Filters out the classes generated by Kotlin to store extension functions
 */
class KotlinExtensionFilter(private val filterContext: FilterContext) : DeadCodeFilter {

    private val regex = ".+Kt\$".toRegex()

    override fun filter(deadCode: DeadCode): DeadCode? {
        // If the class name ends in "Kt", it could be a generated class or a
        // class in the src directory. But if there is a file name without
        // the suffix "kt" in the src dir then the class is a generated class
        val targetPath = deadCode.classNameToPathAnnotation().substringBefore("Kt")
        return if (deadCode.className.matches(regex) &&
                filterContext.isStoredInSrcDir(deadCode.moduleName, targetPath)) {
            LoggerHelper.info("[KotlinExtensionFilter] Ignored: ${deadCode.className}")
            return null
        } else {
            deadCode
        }
    }
}
